### ISSUE TITLE
'CollectionModel' object has no attribute 'timemap_metadatafile'

### ISSUE THREAD

**Issue by QFD-Felix** [oduwsdl/off-topic-memento-toolkit#6] opened 2021-12-16 07:09 UTC
Hello ODU WS-DL,

After installing the program by "pip install otmt", I have an error said: 'CollectionModel' object has no attribute 'timemap_metadatafile'. Do you know where the problem is? How can I solve the problem?

Thank you so much!

**Comment by shawnmjones** [comment] 2021-12-19 17:06
Closing as duplicate of #5.

**Closed as completed by shawnmjones** 2021-12-19 17:06 UTC
Labels: duplicate
