### ISSUE TITLE
'CollectionModel' object has no attribute 'timemap_metadatafile'

### ISSUE THREAD

**Issue by QFD-Felix** [oduwsdl/off-topic-memento-toolkit#5] opened 2021-12-16 07:07 UTC
Hello ODU WS-DL, 

After installing the program by "pip install otmt", I have an error said: 'CollectionModel' object has no attribute 'timemap_metadatafile'. Do you know where the problem is? How can I solve the problem?

Thank you so much!

Regards,

Qiufeng Du

**Comment by shawnmjones** [comment] 2021-12-17 01:01
I think you accidentally closed this. I'll take a look at what may be causing this issue and get back to you.

**Comment by shawnmjones** [comment] 2021-12-17 01:03
I need the exact command that you typed, then I can try to diagnose the issue.

**Comment by shawnmjones** [comment] 2021-12-17 01:09
Also, see #4 if you had installation issues.

**Comment by QFD-Felix** [comment] 2021-12-17 21:32
From my observation, I found that in file /otmt/collectionmodel.py, the file created a class called CollectionModel. In the class init function, you used an if-else statement (line 111 - line 118) to decide whether the working_directory has been created. If it hasn't been created, the program will create a new working directory otherwise the program will load the data from the existing working directory. However, when I have the working directory and try to load the data from the working directory (/tmp/otmt-working/), the problem: 'CollectionModel' object has no attribute 'timemap_metadatafile' will appear. So right now, I have to manually remove the existing working directory (/tmp/otmt-working/) each time before the program execution so the program could create a new working directory each time instead of loading the old working directory. In this way I can get the result from collections: wca(ID: 6296) and fort_mcmuarray(ID: 7368).

**Comment by shawnmjones** [comment] 2021-12-19 17:13
I just ran and got the following output from running `detect_off_topic -i archiveit=7877 -o outputfile.csv -ot csv` :

```
2021-12-19 10:11:09,981 [INFO] __main__: Starting topic analysis run.
2021-12-19 10:11:09,985 [INFO] __main__: Acquiring memento colleciton using input type archiveit
2021-12-19 10:11:09,985 [INFO] __main__: TimeMap measures chosen: {'cosine': 0.12}
2021-12-19 10:11:09,985 [INFO] otmt.input_types: Using input type archiveit
2021-12-19 10:11:09,985 [INFO] otmt.input_types: Working directory /tmp/otmt-working will be used
2021-12-19 10:11:09,986 [INFO] otmt.input_types: Acquiring Archive-It collection 7877
2021-12-19 10:11:12,249 [INFO] charset_normalizer: ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2021-12-19 10:11:12,249 [INFO] charset_normalizer: ascii should target any language(s) of ['Latin Based']
2021-12-19 10:11:12,252 [INFO] charset_normalizer: We detected language [('English', 1.0), ('Dutch', 1.0), ('Norwegian', 1.0)] using ascii
2021-12-19 10:11:12,252 [INFO] charset_normalizer: ascii is most likely the one. Stopping the process.
2021-12-19 10:11:12,262 [INFO] charset_normalizer: ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2021-12-19 10:11:12,262 [INFO] charset_normalizer: ascii should target any language(s) of ['Latin Based']
2021-12-19 10:11:12,263 [INFO] charset_normalizer: We detected language [('English', 1.0), ('Dutch', 1.0), ('Norwegian', 1.0)] using ascii
2021-12-19 10:11:12,263 [INFO] charset_normalizer: ascii is most likely the one. Stopping the process.
2021-12-19 10:11:12,272 [INFO] charset_normalizer: ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2021-12-19 10:11:12,272 [INFO] charset_normalizer: ascii should target any language(s) of ['Latin Based']
2021-12-19 10:11:12,274 [INFO] charset_normalizer: We detected language [('English', 1.0), ('Dutch', 1.0), ('Norwegian', 1.0)] using ascii
2021-12-19 10:11:12,274 [INFO] charset_normalizer: ascii is most likely the one. Stopping the process.
2021-12-19 10:11:12,276 [INFO] otmt.input_types: Discovering raw mementos
2021-12-19 10:11:12,908 [INFO] otmt.input_types: Issuing requests for 12 raw mementos
2021-12-19 10:11:14,879 [INFO] __main__: Processing mementos using TimeMap measure cosine
2021-12-19 10:11:14,879 [INFO] otmt.timemap_measures: Computing cosine score across TimeMap, beginning TimeMap iteration...
2021-12-19 10:11:14,879 [INFO] otmt.timemap_measures: Processing TimeMap 1 of 3
2021-12-19 10:11:14,887 [INFO] otmt.timemap_measures: There are 2 mementos in this TimeMap
2021-12-19 10:11:14,918 [INFO] otmt.timemap_measures: Processing TimeMap 2 of 3
2021-12-19 10:11:14,922 [INFO] otmt.timemap_measures: There are 4 mementos in this TimeMap
2021-12-19 10:11:14,951 [INFO] otmt.timemap_measures: Processing TimeMap 3 of 3
2021-12-19 10:11:14,954 [INFO] otmt.timemap_measures: There are 6 mementos in this TimeMap
2021-12-19 10:11:14,987 [INFO] __main__: computing Simhashes
2021-12-19 10:11:14,987 [INFO] otmt.metadata_calcluations: calculating Simhash for mementos in TimeMap 1 of 3
2021-12-19 10:11:15,005 [INFO] otmt.metadata_calcluations: calculating Simhash for mementos in TimeMap 2 of 3
2021-12-19 10:11:15,027 [INFO] otmt.metadata_calcluations: calculating Simhash for mementos in TimeMap 3 of 3
2021-12-19 10:11:15,060 [INFO] __main__: computing content lengths
2021-12-19 10:11:15,060 [INFO] otmt.metadata_calcluations: calculating content lengths on mementos in TimeMap 1 of 3
2021-12-19 10:11:15,061 [INFO] otmt.metadata_calcluations: calculating content lengths on mementos in TimeMap 2 of 3
2021-12-19 10:11:15,061 [INFO] otmt.metadata_calcluations: calculating content lengths on mementos in TimeMap 3 of 3
2021-12-19 10:11:15,061 [INFO] __main__: detecting languages
2021-12-19 10:11:15,061 [INFO] otmt.metadata_calcluations: calculating languages on mementos in TimeMap 1 of 3
2021-12-19 10:11:15,407 [INFO] otmt.metadata_calcluations: calculating languages on mementos in TimeMap 2 of 3
2021-12-19 10:11:15,463 [INFO] otmt.metadata_calcluations: calculating languages on mementos in TimeMap 3 of 3
2021-12-19 10:11:15,562 [INFO] otmt.metadata_calcluations: calculating content lengths on mementos in TimeMap 1 of 3
2021-12-19 10:11:15,562 [INFO] otmt.metadata_calcluations: calculating content lengths on mementos in TimeMap 2 of 3
2021-12-19 10:11:15,562 [INFO] otmt.metadata_calcluations: calculating content lengths on mementos in TimeMap 3 of 3
2021-12-19 10:11:15,562 [INFO] __main__: saving ouput as type csv
2021-12-19 10:11:15,563 [INFO] __main__: output written to outputfile.csv
2021-12-19 10:11:15,563 [INFO] __main__: Finished analysis run
```

I'm providing this so you have some idea of what output you might have gotten if everything went smoothly.

I'm going to look at the code now.

**Comment by shawnmjones** [comment] 2021-12-19 17:17
When I run it a second time, I can reproduce your issue:

```
2021-12-19 10:15:55,081 [INFO] __main__: Starting topic analysis run.
2021-12-19 10:15:55,082 [INFO] __main__: Acquiring memento colleciton using input type archiveit
2021-12-19 10:15:55,082 [INFO] __main__: TimeMap measures chosen: {'cosine': 0.12}
2021-12-19 10:15:55,082 [INFO] otmt.input_types: Using input type archiveit
2021-12-19 10:15:55,082 [INFO] otmt.input_types: Working directory /tmp/otmt-working will be used
2021-12-19 10:15:55,082 [INFO] otmt.input_types: Acquiring Archive-It collection 7877
2021-12-19 10:15:55,430 [INFO] otmt.collectionmodel: loading data from directory /tmp/otmt-working/timemaps
Traceback (most recent call last):
  File "/Users/smj/.virtualenvs/otmt/bin/detect_off_topic", line 198, in <module>
    cm = otmt.get_collection_model(
  File "/Users/smj/.virtualenvs/otmt/lib/python3.9/site-packages/otmt/input_types.py", line 678, in get_collection_model
    return supported_input_types[input_type](arguments, working_directory)
  File "/Users/smj/.virtualenvs/otmt/lib/python3.9/site-packages/otmt/input_types.py", line 263, in get_collection_model_from_archiveit
    cm = CollectionModel(working_directory)
  File "/Users/smj/.virtualenvs/otmt/lib/python3.9/site-packages/otmt/collectionmodel.py", line 117, in __init__
    self.load_data_from_directory()
  File "/Users/smj/.virtualenvs/otmt/lib/python3.9/site-packages/otmt/collectionmodel.py", line 192, in load_data_from_directory
    mdt = tmdata['mementos']['last']['datetime']
KeyError: 'last'
Exception ignored in: <function CollectionModel.__del__ at 0x10ac3cdc0>
Traceback (most recent call last):
  File "/Users/smj/.virtualenvs/otmt/lib/python3.9/site-packages/otmt/collectionmodel.py", line 139, in __del__
    self.timemap_metadatafile.close()
AttributeError: 'CollectionModel' object has no attribute 'timemap_metadatafile'
```

Thank you for reporting it. The should not happen. The whole point of having a working directory is to cache data in case a poor or interrupted connection causes a failure. That way the OTMT doesn't need to download the data again.

**Comment by shawnmjones** [comment] 2021-12-19 17:32
I believe I have isolated the issue. This is a complex set of failures. Here is what I think is happening:

1. on line 117 of `otmt/collectionmodel.py`, the OTMT executes `load_data_from_directory` to load the cached data
2. on line 192 of the same file, the OTMT tries to read the last memento URI-M from the TimeMap, but it doesn't exist, so Python throws an exception
3. throwing this exception causes the `CollectionModel` class to fall out of scope, which executes its destructor on line 137
4. when the code gets to closing the `timemap_metadatafile` on line 139, it throws yet another exception because the variable was not filled due to the exception thrown in step 2

There are a few problems here:
* the code checks for a corrupt TimeMap by only checking the first memento, **not** also the last memento, so this is an issue - I'm surprised this never came up during testing
* the code fails but never reports at which TimeMap it fails, so we can't further diagnose the issue - I'm going to fix this first so I can see what's happening

It is also possible that a problem exists in the function `otmt/timemap.py:convert_LinkTimeMap_to_dict` where it does not save small TimeMaps properly. Again, I use this function quite heavily throughout the DSA, so I'm surprised that we did not see this sooner.

Thanks again for reporting this.

**Comment by shawnmjones** [comment] 2021-12-19 17:36
I was able to discover the culprit TimeMap by adding `-v` (for verbose logging) to `detect_off_topic`. The culprit, in the case of collection 7877, is at http://wayback.archive-it.org/7877/timemap/link/http://digitalinnovations.ucla.edu/

```
<http://digitalinnovations.ucla.edu/>; rel="original",
<http://wayback.archive-it.org/7877/timemap/link/http://digitalinnovations.ucla.edu/>; rel="self"; type="application/link-format"; from="Tue, 21 Mar 2017 15:45:06 GMT",
<http://wayback.archive-it.org/7877/http://digitalinnovations.ucla.edu/>; rel="timegate",
<http://wayback.archive-it.org/7877/20170321154506/http://digitalinnovations.ucla.edu/>; rel="first memento"; datetime="Tue, 21 Mar 2017 15:45:06 GMT",
<http://wayback.archive-it.org/7877/20170321154512/http://digitalinnovations.ucla.edu/>; rel="memento"; datetime="Tue, 21 Mar 2017 15:45:12 GMT",
```

There is a `rel="first memento"` but no `rel="last memento"` in the TimeMap. Perhaps Archive-It has changed how they handle this. That may explain why I did not encounter this in testing. There are two mementos here, and only one is marked as `first`. I'll have to update the OTMT to *guess* as to the value for `last memento` if Archive-It is not going to support this anymore.

**Closed as completed** 2021-12-19 18:04 UTC
